export const ACTIONS = {
    GET_USER_LIST: 'GET_USER_LIST',
    GET_USER_LIST_SUCCESS: 'GET_USER_LIST_SUCCESS',
    GET_USER_LIST_FAIL: 'GET_USER_LIST_FAIL',
    CLEAR_USER_LIST: 'CLEAR_USER_LIST',
    CLEAR_USER_LIST_SUCCESS: 'CLEAR_USER_LIST_SUCCESS',
};
